### PR TITLE
load project routes before app routes

### LINKED ISSUE #9205: [Bug]: Unable to override `/` route in a project
It seems like we are unable to override `/` route in a project. Probably due to `packages/client/src/main.tsx` is overriding it.

### PR DESCRIPTION
**Pull request by aditya-mitra**
### <samp>🤖 Generated by Copilot at 693d2a2</samp>

This pull request improves the routing functionality of the client package by refactoring and simplifying the custom routes component and moving it to the `RouterService` class. It also removes an unnecessary console log statement from the `RouterService` file.

## References
closes #9205

### <samp>🤖 Generated by Copilot at 693d2a2</samp>

*  Refactored the routing logic to use the `RouterService` class and allow custom routes to be defined and rendered dynamically ([link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-15aaa136b348e19b3b1535e0c6c3f8d11bd9d8d40d76b3800990e2db89734bf3L60), [link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-911327112b6ec08bb7156719dde52135949e3eab7e5e7902930d5a81210d6689L30-R33), [link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-911327112b6ec08bb7156719dde52135949e3eab7e5e7902930d5a81210d6689L38-R47), [link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-dff4789d996b27df598ed44b03b73f0e37bd36de4001e0df2114430a117e04fbL49-R72), [link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-dff4789d996b27df598ed44b03b73f0e37bd36de4001e0df2114430a117e04fbL71-R78))
  * Moved the `CustomRoutes` component from `customRoutes.tsx` to `RouterService.ts` and added a type annotation for the `customRoutes` prop ([link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-911327112b6ec08bb7156719dde52135949e3eab7e5e7902930d5a81210d6689L30-R33))
  * Simplified the filtering and rendering of the custom routes in the `CustomRoutes` component by comparing the whole route and pathname strings ([link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-911327112b6ec08bb7156719dde52135949e3eab7e5e7902930d5a81210d6689L38-R47))
  * Modified the `RouterComp` function in `public.tsx` to load the custom route component for each case in the switch statement, if it exists, or fall back to the default component ([link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-dff4789d996b27df598ed44b03b73f0e37bd36de4001e0df2114430a117e04fbL49-R72))
  * Extracted the logic for loading the custom route component into a separate function called `loadProjectComponent` in `public.tsx` ([link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-dff4789d996b27df598ed44b03b73f0e37bd36de4001e0df2114430a117e04fbL49-R72))
  * Removed the unnecessary console log statement from the `getCustomRoutes` function in `RouterService.ts` ([link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-15aaa136b348e19b3b1535e0c6c3f8d11bd9d8d40d76b3800990e2db89734bf3L60))
  * Removed the unnecessary curly braces around the `RouteElement` variable in the return statement of the `RouterComp` function in `public.tsx` ([link](https://github.com/EtherealEngine/etherealengine/pull/9226/files?diff=unified&w=0#diff-dff4789d996b27df598ed44b03b73f0e37bd36de4001e0df2114430a117e04fbL71-R78))

### <samp>🤖 Generated by Copilot at 693d2a2</samp>

> _Sing, O Muse, of the skillful coder who refactored_
> _The custom routes component, and made it more ordered_
> _He removed the `console.log` from the `getCustomRoutes` function_
> _Like Zeus hurling his thunderbolts to end the earth's corruption_

## QA Steps

Screenshot 2023-11-07 at 6 49 34 PM

## Checklist
- If this PR is still a WIP, convert to a draft
- When this PR is ready, mark it as "Ready for review"
- [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- Changes have been manually QA'd 
- Changes reviewed by at least 2 approved reviewers

### CODE REVIEW

**Review by hanzlamateen — CHANGES_REQUESTED** [review]
I am getting following error on MT project as it has redirect implemented in it.

image

**Comment by HexaField** [comment]
> I am getting following error on MT project as it has redirect implemented in it.
> 
> image

is this perhaps due to navigating from a tailwind route to a mui route, or vice versa?

**Comment by aditya-mitra** [comment]
It was a react-router issue with `navigate`. If a reload was done on the same page there would be no errors.
Using native `location.replace` produced no error. Best guess is probably race condition where while Engine was initialized when the page got navigated and again the Engine was reinitialized.
I have pushed a fixed for it.

**Review by hanzlamateen — APPROVED** [review]
Seems to be working fine now.

**Review by HexaField — APPROVED** [review]

**Pull request merged**
