### PR TITLE
improve(texture compression): improvements in dialog UI

### LINKED ISSUE #8222: [Bug]: Texture Compression workflow needs improved UI
Current UI is not very intuitive:

Screenshot 2023-07-05 at 11 05 01 AM

Improvements:
- Info / tooltips for each setting. See documented KTX2EncodeOptions in KTX2Encoder.ts
- Quality setting should have a visible slider
- After hitting "compress", the UI should dissapear, and there should be a progress circle in the file browser next to the pending "*.ktx2" file, indicating that the ktx2 file is being generated.

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

- added info for all inputs
- added slider for 
- made the compression loading UI more intuitive

image

## References

closes #8222 

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

**Review by HexaField — CHANGES_REQUESTED** [review]
- Quality should have a number identifying what the quality level is
- Should include compressionLevel setting as slider with number

**Review by speigg — CHANGES_REQUESTED** [review]
Looks significantly better, but let's expose all the options available in KTX2EncodeOptions, including `uastc` flags and the `normalMap` flag. Also, not sure why the `srgb` option has been flipped to `linear`; lets expose all these options as specified in the ktx2 encoder for clarity, with the relevant information in the tooltip hints. Options relevant only to etc1s or uastc should only be visible when that mode is selected (e.g., shouldn't see qualityLevel or compressionLevel when using uastc mode, shouldn't see uastcFlags when using etc1s mode). 

```ts
export interface KTX2EncodeOptions {
  /**
   * If true, the input is assumed to be in sRGB space. Be sure to set this correctly! (Examples: True on photos, albedo/spec maps, and false on normal maps.)
   * @default false
   */
  srgb?: boolean
  /**
   * Sets the ETC1S encoder's quality level, which controls the file size vs. quality tradeoff
   * Range is [1,256]
   * @default 128
   */
  qualityLevel?: number
  /**
   * The compression_level parameter controls the encoder perf vs. file size tradeoff for ETC1S files
   * It does not directly control file size vs. quality - see qualityLevel
   * Range is [0,6]
   * @default 2
   */
  compressionLevel?: number
  /**
   * If true, the encoder will output a UASTC texture, otherwise a ETC1S texture.
   * @default false
   */
  uastc?: boolean
  /**
   * Use UASTC Zstandard supercompression. Use with uastc = true
   * @default false
   */
  uastcZstandard?: boolean
  /**
   * Sets the UASTC encoding performance vs. quality tradeoff, and other lesser used UASTC encoder flags.
   * This is a combination of flags. See UASTCFlags
   */
  uastcFlags?: number
  /**
   * Tunes several codec parameters so compression works better on normal maps.
   * @default false
   */
  normalMap?: boolean
  /**
   * If true, the encoder will generate mipmaps.
   * @default false
   */
  mipmaps?: boolean
  /**
   * If true the source images will be Y flipped before compression
   * @default false
   */
  yFlip?: boolean
}
```

Also, a progress indicator to show that something is happening would be valuable.

**Comment by aditya-mitra** [comment]
Implemented the changes!

> Also, a progress indicator to show that something is happening would be valuable.

We have implemented a progress indicator which shows like this:

Screenshot_20230713_215309

**Review by HexaField — CHANGES_REQUESTED** [review]
- Close button does not close the modal
- Quality level and compression level should be available in UASTC mode

**Review by HexaField — APPROVED** [review]

**Comment by HexaField** [comment]
whoops, forgot about `Quality level and compression level should be available in UASTC mode`

**Comment by aditya-mitra** [comment]
Actually Gheric had mentioned this:
> shouldn't see qualityLevel or compressionLevel when using uastc mode, shouldn't see uastcFlags when using etc1s mode

So, I only implemented in UASTC mode. Should I make it available for both modes?

**Comment by HexaField** [comment]
> Actually Gheric had mentioned this:
> > shouldn't see qualityLevel or compressionLevel when using uastc mode, shouldn't see uastcFlags when using etc1s mode
> 
> So, I only implemented in ETC1S mode. Should I make it available for both modes?

Yes

**Pull request merged**
