### PR TITLE
fix block user functionality

### LINKED ISSUE #8604: [Bug] Unblocking someone adds them as a friend
Should just remove all `user-relationship`s

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

I tried to do this (in many ways) without using the `_` (underscore) method. The major problem is still that feathers calls the other service methods **only when the current service method finishes completely**.

### <samp>🤖 Generated by Copilot at 756c5ad</samp>

Improved user relationship service in `server-core` package. Used type definition for query parameters and optimized blocking relationship removal in `user-relationship.hooks.ts`.

## References
closes #8604 

### <samp>🤖 Generated by Copilot at 756c5ad</samp>

* Imported `UserRelationshipParams` type from `user-relationship.class` file to define query parameters for user relationship service methods ([link](https://github.com/EtherealEngine/etherealengine/pull/9140/files?diff=unified&w=0#diff-c436ada5acdb4c03cffc35e4cf7b0012d3bba28d9c4f3c29a4f74f3b35393285L45-R45))
* Modified `clearBlockingRelationships` function to use `_remove` method instead of `remove` method of user relationship service to delete multiple documents that match the query condition of either user or related user being blocked by the other ([link](https://github.com/EtherealEngine/etherealengine/pull/9140/files?diff=unified&w=0#diff-c436ada5acdb4c03cffc35e4cf7b0012d3bba28d9c4f3c29a4f74f3b35393285L112-R123))
* Typed query condition of `clearBlockingRelationships` function as `UserRelationshipParams` to ensure consistency with service interface ([link](https://github.com/EtherealEngine/etherealengine/pull/9140/files?diff=unified&w=0#diff-c436ada5acdb4c03cffc35e4cf7b0012d3bba28d9c4f3c29a4f74f3b35393285L112-R123))

### <samp>🤖 Generated by Copilot at 756c5ad</samp>

> _Sing, O Muse, of the skillful coder who improved_
> _The user relationship service, a noble deed indeed,_
> _By importing `queryParameters`, a type well-defined,_
> _And clearing blocking ties with a swifter method's speed._

## QA Steps
_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

## Checklist
- If this PR is still a WIP, convert to a draft
- When this PR is ready, mark it as "Ready for review"
- [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- Changes have been manually QA'd 
- Changes reviewed by at least 2 approved reviewers

### CODE REVIEW

**Comment by aditya-mitra** [comment]
checked #8604 
it does happen in the latest dev (after this fix)


[6da65e26-04f6-4695-b087-e081f24ce6cc.webm](https://github.com/EtherealEngine/etherealengine/assets/55396651/25da41a7-dc8f-42c7-b14a-787defce8741)

**Comment by barankyle** [comment]
I tried triggering this on the latest version of dev on my local machine, and saw a different issue than unblocked users getting made friends; blocking was not working at all. Looking further, it seemed to be that the blocking/blocked user-relationships were getting removed right after they were made. I think it's because line 112 of user-relationship.hooks.ts, `context.app.service(userRelationshipPath).remove`, doesn't have an `await` before it. I think it was starting to remove existing relationships in the hook, moving on and creating the new relationships in the actual service method call, then the removal was finally finishing and deleting the just-created relationships. 

When I added an await before the remove call in clearBlockingRelationships, everything appeared to work. The blocking/blocked relationships were now present after being created, and removing a block was just removing both of those relationships, not creating friend relationships between the users. Is there something I'm missing?

**Comment by aditya-mitra** [comment]
> I tried triggering this on the latest version of dev on my local machine, and saw a different issue than unblocked users getting made friends; blocking was not working at all. Looking further, it seemed to be that the blocking/blocked user-relationships were getting removed right after they were made. I think it's because line 112 of user-relationship.hooks.ts, `context.app.service(userRelationshipPath).remove`, doesn't have an `await` before it. I think it was starting to remove existing relationships in the hook, moving on and creating the new relationships in the actual service method call, then the removal was finally finishing and deleting the just-created relationships.
> 
> When I added an await before the remove call in clearBlockingRelationships, everything appeared to work. The blocking/blocked relationships were now present after being created, and removing a block was just removing both of those relationships, not creating friend relationships between the users. Is there something I'm missing?

You were right. There should have been an `await`.
When I rechecked in on my machine, I found it to be flaky before adding the `await`.

**Comment by barankyle** [comment]
I think we can roll back the change to `._remove`. When I was testing it, it seemed fine with the only change from dev being `await`ing the original call to `.remove`.

**Review by barankyle — APPROVED** [review]

**Pull request merged**
