### PR TITLE
feat(projects): move project download button to file browser panel

### LINKED ISSUE #7903: Move project "download" button into File Browser panel
I keep pressing this download button accidentally when I mean to update the project. Let's move it into the file browser. 

image

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

image

## References

closes #7903 

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

**Comment by HexaField** [comment]
Let's move the button next to the refresh button

**Comment by aditya-mitra** [comment]
> Let's move the button next to the refresh button

@HexaField The previous download button was only for downloading projects. Since the refresh button belongs to the `FileBrowserContentPanel`, do we also want to handle downloading of individual files?

**Comment by HexaField** [comment]
> > Let's move the button next to the refresh button
> 
> @HexaField The previous download button was only for downloading projects. Since the refresh button belongs to the `FileBrowserContentPanel`, do we also want to handle downloading of individual files?

Yeah we want this in the file browser UI itself

**Comment by aditya-mitra** [comment]
I have now moved the download button to the file browser UI !
image

**Review by HexaField — CHANGES_REQUESTED** [review]
To protect against abuse, let's allow the downloader to only allow downloads from `/projects/*` paths, such that any other path (including `/projects`) are disallowed. This should be done in the service, and return an Error otherwise.

**Review by HexaField — CHANGES_REQUESTED** [review]
Works great from the admin panel, but when I click the download button in the file browser in the studio, it downloads as `undefined.zip`

**Comment by aditya-mitra** [comment]
> Works great from the admin panel, but when I click the download button in the file browser in the studio, it downloads as `undefined.zip`

Fixed this!

**Comment by HexaField** [comment]
Last thing, let's hide the button for non-project directories. (nested directories in a project are fine)

**Comment by aditya-mitra** [comment]
> Last thing, let's hide the button for non-project directories. (nested directories in a project are fine)

Sure. Implementing this!

**Review by HexaField — APPROVED** [review]

**Pull request merged**
