### PR TITLE
(Chore): Moved `mui` components under `primitives/mui`

### LINKED ISSUE #7764: Update existing components in UI Library
1. Move existing component to /package/ui/src/primitives/mui/
2. Duplicate component in /package/ui/src/primitives/tailwind/
3. Rewrite component in tailwind
4. Update _template and other components to be consistent when needed

Please make sure these requirements are met for each component:

- Should be a pure Component if possible - no side effects, memo component: export default memo(Component)
- Should have defaultProps and displayName in index.tsx to facilitate Stories, states, and testing
- Stories for each component state / variant (focus, disabled, error, primary, secondary, etc)
- Should have tests to verify states, variants, interactions, etc

### PR DESCRIPTION
**Pull request by Abhijay007**
## Summary

- Moved `mui` components under `primitives/mui`
- changed respective imports for the components

## References

closes #7764 

## Checklist
- [x] When this PR is ready, mark it as "Ready for review"
- [x] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)

### CODE REVIEW

**Comment by Abhijay007** [comment]
@jerknose, I tried to change the base branch to `7763-create-pure-components-write-stories-default-props-and-tests-for-ui-library` but this PR is covering some commits from the `dev` branch too as I pulled the `dev`, so I skipped the branch change you can change that if needed.

**Comment by Abhijay007** [comment]
some imports left over

**Review by jerknose — APPROVED** [review]

**Review by speigg — APPROVED** [review]

**Comment by speigg** [comment]
Hmm, I shouldn't have enabled auto-merge on this, it's causing build errors

**Comment by Abhijay007** [comment]
Ya, I think there is problem in rebase that causes broken build, you can
revert this if you want to, I will fix this PR

**Pull request merged**
