### PR TITLE
redirect to original location after login

### LINKED ISSUE #9524: Redirect to homepage if user doesn't have studio permission
Currently it displays a blank page. Ideally it should redirect to homepage where user should login. And once user has logged in then he should be redirected back to studio.

Same behavior should be done for admin panel.

If there is any redirect url in the query params of homepage, then it should show message that after login, you will be redirected to thats url.

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

- Redirect to the studio's location after logging in
- Redirect to admin location when after logging in
- Add the navigation state when routing from studio or admin to react-route's navigate state.

## References
closes #9524 

## QA Steps

Studio

https://github.com/EtherealEngine/etherealengine/assets/55396651/3ccd91c2-9158-4fe3-8fe6-7d22bbd17846

Admin

https://github.com/EtherealEngine/etherealengine/assets/55396651/f9ddfd0a-c309-4351-80c3-ebda96bb1a7e

### CODE REVIEW

**Comment by hanzlamateen** [comment]
@aditya-mitra just wondering if the redirect/from url can in query string on `sigin page` to persist it between refresh?

**Comment by hanzlamateen** [comment]
I think he can get ride of that initial `/` or `%2F` as well 
image

**Review by hanzlamateen — APPROVED** [review]
Seems to be working fine. Adding @HexaField to give it a second look.

**Review by speigg — APPROVED** [review]

**Comment by speigg** [comment]
looks good to me!

**Review by HexaField — APPROVED** [review]

**Pull request merged**
