### PR TITLE
Changes for user service to use schema, knex & feathers 5

### LINKED ISSUE #8368: Migrate user service to feathers 5

### PR DESCRIPTION
**Pull request by hanzlamateen**
## Summary

_A summary of changes being made in this PR_

Also merge:

https://github.com/EtherealEngine/ee-bot/pull/37
https://github.com/EtherealEngine/ee-development-test-suite/pull/42

## References

#7645, closes #8368

## Checklist
- [x] If this PR is still a WIP, convert to a draft
- [x] When this PR is ready, mark it as "Ready for review"
- [x] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [x] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

**Review by barankyle — CHANGES_REQUESTED** [review]
Found a few issues when testing this:

Login is failing because of make-initial-admin.ts, specifically when it tries to find how many admins there are via scope.find. That scope.find is being passed $select: [id'], and in the updated scope.find, that means that `data` that's returned only has an id on it. But, on line 58, it's trying to pull `type` off of the returned scopes. This 

Starting a recording is failing because of the API call to recording.create. Not sure where in that process, but the error message returned is "data.map is not a function". This happens with any combination of items to record, even no items selected. (Recording is the far-right button in the media controls at the top when in an instance, icon is a picture camera

**Comment by hanzlamateen** [comment]
> Found a few issues when testing this:
> 
> Login is failing because of make-initial-admin.ts, specifically when it tries to find how many admins there are via scope.find. That scope.find is being passed $select: [id'], and in the updated scope.find, that means that `data` that's returned only has an id on it. But, on line 58, it's trying to pull `type` off of the returned scopes. This
> 
> Starting a recording is failing because of the API call to recording.create. Not sure where in that process, but the error message returned is "data.map is not a function". This happens with any combination of items to record, even no items selected. (Recording is the far-right button in the media controls at the top when in an instance, icon is a picture camera

Fixed, Kindly have a look now.

**Comment by barankyle** [comment]
Still seeing problems. A new one is that the media controls are not appearing after the connection to the media server is made; the 'Connecting' message goes away, but the start/stop audio/video/facetracking buttons don't appear.

I'm still also seeing issues with starting a recording. In recording.hooks.ts:populateUser, it's throwing `data.filter is not a function`. Result is an object that is not an array itself, nor does it have a `data` child that is an array.

**Comment by hanzlamateen** [comment]
> Still seeing problems. A new one is that the media controls are not appearing after the connection to the media server is made; the 'Connecting' message goes away, but the start/stop audio/video/facetracking buttons don't appear.
> 
> I'm still also seeing issues with starting a recording. In recording.hooks.ts:populateUser, it's throwing `data.filter is not a function`. Result is an object that is not an array itself, nor does it have a `data` child that is an array.

Both of the above are fixed on my end now. Please cross check.

image

**Review by barankyle — APPROVED** [review]

**Pull request merged**
