### PR TITLE
feat(TransformProperty): local transform component mode

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

Added a boolean input to use `LocalTranformComponent` when the input is checked.

image

## References

closes https://github.com/EtherealEngine/etherealengine/issues/8432

## Checklist
- [ ] If this PR is still a WIP, convert to a draft
- [ ] When this PR is ready, mark it as "Ready for review"
- [ ] [ensure all checks pass](https://github.com/etherealengine/etherealengine/wiki/Testing-&-Contributing)
- [ ] Changes have been manually QA'd
- [ ] Changes reviewed by at least 2 approved reviewer

## QA Steps

_List any additional steps required to QA the changes of this PR, as well as any supplemental images or videos._

### CODE REVIEW

**Review by HexaField — CHANGES_REQUESTED** [review]
this works fine, but we cannot update transform properties on the TransformComponent the same way we do with LocalTransformComponent (via the gizmo), we need to compute and update the TransformComponent directly, or it has incorrect transformations applied and sometimes does not work, snapping back to the original position. We still need to update the gizmo accordingly

**Review by HexaField — CHANGES_REQUESTED** [review]
Using the vector3 scrubbers in the properties panel when using non local transform resets all the values to 0

**Comment by speigg** [comment]
IMO we should always be editing the local transform by default, and have the option to view the world transform (by modifying the local transform behind the scenes).

**Review by HexaField — CHANGES_REQUESTED** [review]
this needs to be rewritten to work with our new snapshots concept

**Review by dinomut1 — APPROVED** [review]
Looks like this works as intended after resolving merge conflicts

**Pull request merged**
